# Makefile.dep created Tue Feb  1 20:56:38 PST 2022
debug.o: debug.cpp debug.h util.h util.tcc
util.o: util.cpp debug.h util.h util.tcc
main.o: main.cpp listmap.h debug.h xless.h xpair.h listmap.tcc util.h \
 util.tcc
